### ISSUE TITLE
App crashes after back press

### ISSUE THREAD

**Issue by joneskm** [mosaicnetworks/babble-android#59]
When restarting the app after pressing the back button, the app crashes. Stacktrace:

```
Caused by: java.lang.RuntimeException: BabbleConstants already initialised
        at io.mosaicnetworks.babble.node.BabbleConstants.initialise(BabbleConstants.java:120)
        at io.mosaicnetworks.babble.configure.BaseConfigActivity.onCreate(BaseConfigActivity.java:137)
        at io.mosaicnetworks.sample.MainActivity.onCreate(MainActivity.java:55)
        at android.app.Activity.performCreate(Activity.java:6855)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2656)
```

The underlying issue is that the activities are re-created when the app is re-started however static variables persist.

**Comment by jonknight73** [comment]
Hold off this, there are some changes in the workflow pending. 

There is a TODO: comment highlighting a similar issue, but it makes sense to fix the refactored version rather that do it twice.
